### ISSUE TITLE
ICG could have a wider scope

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-html#1]
Why you are proposing a single ICG that is tied to JUST the HTML WG?  Why not proposing a wider that includes incubation for the WebApps WG as well? 

Since the ICG is supposed to do its job "by facilitating communication with developers at large" how are these developers supposed to know who to talk to since they will probably not understand the somewhat arbitrary "division of labour" that exists between the W3C Web Platform WGs?

**Comment by darobin** [comment]
I agree, having just one incubator (for Interaction) is a lot more readable from the outside. The Web Incubation Community of Developers — WICD (it's wicked!).

**Comment by plehegar** [comment]
Scope for the ICG is now "Web Platform"
https://github.com/w3c/charter-html/commit/4ea336f31cc730c72876c2aca84ff53f3f17c81b
