### ISSUE TITLE
[group-charter] Expectations re "Activity summaries around the github repositories activity are provided"

### ISSUE THREAD

**Issue by AFBarstow** [w3c/charter-html#102]
The latest draft includes the statement "The Chairs must ensure that regular activity summaries around the github repositories activity are provided." What are the (specific) expectations here? 

Is Github's "pulse" data sufficient to meet this requirement? For example:
- https://github.com/w3c/WebComponents/pulse/
- https://github.com/w3c/WebComponents/pulse/monthly

**Comment by plehegar** [comment]
"pulse" is closed to what we're looking but we're looking at generating an email report as well.
Modern tooling is supposed to fill the gap here so the expectation is to make this automatic.

**Comment by AFBarstow** [comment]
Since there are a number of variables here (especially "supposed" v-a-v the "tools will save us"), a "must" requirement isn't appropriate. Either delete this requirement since Github Pulse status will auto-magically be available or soften the requirement to something like:

[[
In addition to the group's Github activity being available via Github's "Pulse" service, the group may produce additional activity reports.
]]

**Comment by plehegar** [comment]
I'd rather keep the must for the moment. This is an important part of ensuring we don't exclude folks from the conversations in our move to github.
