### ISSUE TITLE
Acronym expansion

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-html#105]
Minor nit...

In section 3.1 (Recc track deliverables), there is:
"A specification defining how user agents map HTML elements and attributes to platform accessibility application programming interfaces (APIs)."

The API acronym has been used multiple times on the page already, and is proprely expanded the first time it's used (in the opening paragraph), so there's no need to expand it here.

**Comment by plehegar** [comment]
https://github.com/w3c/charter-html/commit/f3735271b7f50415bf547b027aaf5a53026aab1e
