### ISSUE TITLE
Call it like it is

### ISSUE THREAD

**Issue by AFBarstow** [w3c/charter-html#107]
The proposed group is a merge of the Web Applications WG and the HTML WG. As such, the group's name should reflect this scope and be named similarly such as:
- HTML and Web Applications WG [or v-v]
- HTML and Web APIs WG [or v-v]

A quick Web search indicates "Web Platform" is the consortium's webplatform.org project which is a completely different scope than this WGs'. Likewise, wikipedia says "Open Web Platform" is a nearly unlimited scope of standards including CSS, HTTP and RDFa, thus again, not representative of the proposed WG's scope.

If/when this super-duper group is split up, a new name might naturally fall out but until then, please use a name that is self-evident.

**Comment by plehegar** [comment]
I think this one can be closed.
