### ISSUE TITLE
unclear about wg leadership bullet point

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/charter-html#11]
> WG Leadership: process (avoid derailment, drive decision, drive schedule), technical (expertise in use and implementation), leadership skills/credibility, no W3C Team, no editor

this is unclear "no W3C Team, no editor" ??

**Comment by LJWatson** [comment]
Perhaps a reference to the fact a chair should not be a member of W3C team? Not sure about editor part - perhaps that the two roles should not fall to one person?

**Comment by darobin** [comment]
I think that indeed the idea is that whoever is in charge of leadership should not be an editor or team.

You need checks and balances; I don't think I need to give you an example why.

**Comment by rubys** [comment]
@darobin: dare I add: the leadership shouldn't be exclusively from browser vendors, nor should browser vendors have veto power over participation.  I don't think I need to give you an example of this occurring either.  :-(
