### ISSUE TITLE
Styling for readability

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-html#115]
During TPG's internal review of the Web Platform WG charter, @IanPouncey noted:
“The visual formatting of the nested definition lists makes it quite hard to read by the way, it could do with some simple changes to the spacing and maybe font weight of the outer <dt> elements."

Can this be easily updated, or is it something that needs changing in a template buried somewhere deep in the depths of W3C machinery?

**Comment by chaals** [comment]
The charter is a static HTML document, so feel free to make PRs.
