### ISSUE TITLE
Using CfC for Decisions

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-html#117]
Announcing tentative decisions in the draft minutes (not even final) is not enough; any issue worthy of needing a formal decision is also worthy of a separate email, saying ‘Call for Consensus/CfC: xxx’. Many people do not have the time to check draft minutes every week, but everyone deserves to be alerted of pending decisions. Also, even draft minutes are sometimes delayed. Please revise the policy to use explicit CfC notifications.

**Comment by wayneca** [comment]
Does this mean that after a meeting where decisions were made, there would be a single CfC with a list of all decisions made at the meeting and it would be a CfC for final concensus on what was agreed at the meeting?  That would be fine.

Having a different CfC for each decision would be a lot of work where we'd expect typically there wouldn't be objections.

**Comment by dwsinger** [comment]
> On Sep 4, 2015, at 17:46 , Wayne Carr notifications@github.com wrote:
> 
> Does this mean that after a meeting where decisions were made, there would be a single CfC with a list of all decisions made at the meeting and it would be a CfC for final concensus on what was agreed at the meeting? That would be fine.
> 
> Having a different CfC for each decision would be a lot of work where we'd expect typically there wouldn't be objections.

as long as the email says clearly CfC or Call For Consensus, that’s fine.  It alerts people.  Clearly it helps if the subject gives a clue as to what it’s about.

> —
> Reply to this email directly or view it on GitHub.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by chaals** [comment]
I _think_ this is the same issue as #118 - people need to find easily where to watch and follow formal stuff from the group such as a Call for Consensus to make a First Public Working Draft, as well as decisions such as actually publishing one without following the various technical lists of the group, or even particularly closely following the group's work at all.

**Comment by AFBarstow** [comment]
The issue as recorded mixes and conflates a few things:
- "Announcing tentative decisions in the draft minutes (not even final) is not enough". "Not enough" for what? What exactly is the problem and please note the draft charter already explicitly
  stipulates that all meeting minutes are provisional for 10 days after the minutes are announced.
- "any issue worthy of needing a formal decision is also worthy of a separate email, saying ‘Call for Consensus/CfC: xxx’". What does "issue" mean here? Is this github Issues, process issues, technical issues? My expectation is this group will use CfCs to record consensus for a variety of reasons and I don't think the charter should micro-manage/constrain how the group uses its CfCs.
- "Many people do not have the time to check draft minutes every week, but everyone deserves to be alerted of pending decisions. Also, even draft minutes are sometimes delayed. Please revise the policy to use explicit CfC notifications.". Please see the Decision Policy in the draft charter and the feedback above.

To help minimize the disruption of ongoing work in WebApps and HTMLWG, my expectation is those two groups will continue to use their existing mail lists as before, and a new list for the proposed group (say public-webplatform or public-webplatform-admin) should be created and the staff/chairs should make sure all meeting minutes are announced (f.ex. Cc'ed) on this new list (and (optionally) to the existing list). Of course this new list would also be used for group-wide CfCs.

**Comment by dwsinger** [comment]
> On Sep 17, 2015, at 8:12 , Arthur Barstow notifications@github.com wrote:
> 
> The issue as recorded mixes and conflates a few things:
> 
>   • "Announcing tentative decisions in the draft minutes (not even final) is not enough". "Not enough" for what?

To be visible to the entire community.  We’re talking about formal declarations of consensus and decisions here. They cannot be buried in draft minutes.

> What exactly is the problem and please note the draft charter already explicitly
> stipulates that all meeting minutes are provisional for 10 days after the minutes are announced.

That’s a completely different question.

>   • "any issue worthy of needing a formal decision is also worthy of a separate email, saying ‘Call for Consensus/CfC: xxx’". What does "issue" mean here?

Where a formal Decision of the Working Group is being made.

> Is this github Issues, process issues, technical issues? My expectation is this group will use CfCs to record consensus for a variety of reasons and I don't think the charter should micro-manage/constrain how the group uses its CfCs.

I am talking about any case where the chairs want to, or need to, claim that they have the consensus of the working group.

>   • "Many people do not have the time to check draft minutes every week, but everyone deserves to be alerted of pending decisions. Also, even draft minutes are sometimes delayed. Please revise the policy to use explicit CfC notifications.". Please see the Decision Policy in the draft charter and the feedback above.

That’s what the comment was about in the first place. Burying formal consensus calls in _draft minutes_ is not appropriate.

> To help minimize the disruption of ongoing work in WebApps and HTMLWG, my expectation is those two groups will continue to use their existing mail lists as before, and a new list for the proposed group (say public-webplatform or public-webplatform-admin) should be created and the staff/chairs should make sure all meeting minutes are announced (f.ex. Cc'ed) on this new list (and (optionally) to the existing list). Of course this new list would also be used for group-wide CfCs.

You’re talking about minutes.  I’m talking about formal claims of consensus, formal decisions of the WG, and so on.

I think what the HTML working group does today works well; Paul sends an email announcing the CfC and the deadline. It’s evident from the subject line that he’s determining whether there is consensus.  Anyone can easily notice; they don’t need to read all the minutes.  Please continue this practice. Thank you.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by AFBarstow** [comment]
David - for several years, WebApps has been using CfCs to record formal decisions as documented in the group's [Work Mode document](http://www.w3.org/2008/webapps/wiki/WorkMode). HTMLWG adopted many parts of WebApps' work mode including CfCs and my expectation is the combined group will continue to follow that practice. 

I prefer the charter to not be overly prescriptive regarding the operational aspects of the group. However, I don't see any particular harm with adding a link to the group's "work mode" document (as is done now in [WebApps' charter](http://www.w3.org/2014/06/webapps-charter.html#communication)).

@plehegar please create the group's home page now (f.ex. github.com/WebPlaformWG) so we can start populating with documents and proposals for things like the group's work mode. ([Issue 99](https://github.com/w3c/charter-html/issues/99)).

**Comment by dwsinger** [comment]
> On Sep 20, 2015, at 4:34 , Arthur Barstow notifications@github.com wrote:
> 
> David - for several years, WebApps has been using CfCs to record formal decisions as documented in the group's Work Mode document. HTMLWG adopted many parts of WebApps' work mode including CfCs and my expectation is the combined group will continue to follow that practice.

Maybe we’re aligned.  For several years, HTML has announced formal calls for consensus using an email with CfC in the title, and the subject of the consensus. That’s all I am asking for; a continuation of the HTML WG’s practice.

What I don’t want to have happen is the chairs being accused of claiming consensus when the attempt to establish consensus wasn’t very visible. That gets messy.

> I prefer the charter to not be overly prescriptive regarding the operational aspects of the group. However, I don't see any particular harm with adding a link to the group's "work mode" document (as is done now in WebApps' charter).
> 
> @plehegar please create the group's home page now (f.ex. github.com/WebPlaformWG) so we can start populating with documents and proposals for things like the group's work mode. (Issue 99).
> 
> —
> Reply to this email directly or view it on GitHub.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by chaals** [comment]
Yes, I think we are pretty much aligned.

The request I see is that the charter says where to find things like a call for consensus, or minutes that include (potential) resolutions.

**Comment by plehegar** [comment]
https://github.com/w3c/charter-html/commit/136bb1fedafc536bf23fda9a562a0fb574608e8b

**Comment by plehegar** [comment]
https://github.com/w3c/charter-html/pull/129
