### ISSUE TITLE
Find formal resolutions of the group

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-html#118]
The charter must clearly identify where people can find formal resolutions of the group. This could be as simple as identifying a particular mailing list to which all such announcements will be sent.

**Comment by wayneca** [comment]
That could be combined with the other one about people not wanting to look in meeting minutes for decisions.  Wherever that was, the meeting ones could have the notice about asking for asynchronous reconsideration.

**Comment by LJWatson** [comment]
Given that different groups within the WG will use different work modes, email sounds like a reasonable option. Either a specific list, or the primary WG list - perhaps with a required keyword in the subject line.

**Comment by plehegar** [comment]
https://github.com/w3c/charter-html/commit/136bb1fedafc536bf23fda9a562a0fb574608e8b

**Comment by plehegar** [comment]
https://github.com/w3c/charter-html/pull/129
