### ISSUE TITLE
Work on HTML

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/charter-html#130]
Given that the vast majority of development and maintenance work on defining the **browser implementation aspects** of HTML is being carried out at the WHATWG, what are the working groups reasons against dropping the forking/republication of HTML at W3C? It would be particularly helpful to understand what the browser vendors thoughts are.

**Comment by dwsinger** [comment]
> On Oct 1, 2015, at 2:07 , stevefaulkner notifications@github.com wrote:
> 
> Given that the vast majority of development and maintenance work on defining the browser implementation aspects of HTML is being carried out at the WHATWG, what are the working groups reasons against dropping the forking/republication of HTML at W3C? It would be particularly helpful to understand what the browser vendors thoughts are.

Speaking only for myself here, W3C Recommendations are subject to the Patent Policy, which is probably important for such a key spec.

> —
> Reply to this email directly or view it on GitHub.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by stevefaulkner** [comment]
> Speaking only for myself here, W3C Recommendations are subject to the Patent Policy, which is probably important for such a key spec.

@dwsinger Do you mean you are not presenting any official Apple position?

**Comment by dwsinger** [comment]
> On Oct 1, 2015, at 13:54 , stevefaulkner notifications@github.com wrote:
> 
> Speaking only for myself here, W3C Recommendations are subject to the Patent Policy, which is probably important for such a key spec.
> 
> Do you mean you are not presenting any official Apple position?

I never represent official Apple positions (the board decides those, or at least above my grade) -:(.  I mean, I haven’t even had time to talk to my colleagues, but this point is sufficiently obvious (and at least contributed to the motivation to do HTML5 at the W3C) to make it immediately.

David Singer
Manager, Software Standards, Apple Inc.
