### ISSUE TITLE
Incubation and new deliverables

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-html#140]
The proposed charter states:

> The following deliverables may be developed as Recommendation track documents, if there is consensus in the Working Group that incubation suggests success:
[...]

I think this statement is OK, but would be better to adopt a more general version:

> Additional deliverables may be developed as Recommendation track documents, if if they fit in the scope of the working group and if there is consensus in the Working Group that incubation suggests success. The following documents are likely candidates:
[...]

Especially given the later statement that the WG will recharter if/when it adds any new deliverable, generalizing the above sentence does not introduce any risk.

**Comment by chaals** [comment]
Hmm. The idea is that those specific things are already authorised as deliverables, without a charter change.

They're a few items the group has worked on, and would continue with if there were more implementor interest.

**Comment by frivoal** [comment]
> Hmm. The idea is that those specific things are already authorised as deliverables, without a charter change.

That's not obvious from the existing prose. I don't disagree, but then it should be clarified.

> If the Working Group decides to add new Recommendation-track deliverables <ins>other than the ones listed in this section</ins> then it will recharter [...]. Those listed in this section may be taken on without rechartering.

And I stand by the suggestion in my first comment, which seems compatible with this. Its probably not strictly necessary, as it would be possible even we said nothing at all, but I find it clarifies how the working group intends to work, and so is helpful.
