### ISSUE TITLE
Relation with WICG

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-html#141]
The proposed charter states:

> The Working Group will not adopt new proposals until they have matured through the Web Platform Incubator Community Group or another similar incubation phase.

This statement is not new, but when it was initially introduced, it was described as an experiment. Is it still an experiment? Have we drawn any conclusions form this experiment yet, or does it need to run for a while longer? 

If it is indeed an experiment, even if it has not yet run its course to completion, we ought to be able to agree on what hypothesis it is testing, and what kind of data needs to be gathered to evaluate whether or not it is successful.

The closest attempt I've seen at doing that is https://github.com/WICG/admin/issues/29, but it stalled almost immediately.

**Comment by chaals** [comment]
IMHO:
The experiment is still happening. This charter is taking work out of incubation for the first time Web Platform has seriously tried it. (18 months into our existence…)

A few things I want to see:

- How long does it take us to get work moved over ?

So far I would say too long - as well as the 4-week charter review mandated by Process that we have not started yet, we've been at this for about 6 weeks. If that happens again I'll be pushing for a change in how we do this.

- Is there a community in WICG that has a sense of moving stuff toward being a W3C standard, or is it just a place for big companies to do *de facto* standards without having to follow a consensus process?

Hard to say, overall. It seems that there are data to support either hypothesis at the moment. The good feature of WICG, that it is possible to do an experiment easily and fail fast, also means the data we get are hard to interpret.

- When do we need to incubate from scratch, when is something an incremental step that should be done in the WG direct?

Again, hard to say. My initial feeling is that this is hard to define by rules, and we'll end up calling it as we see it on each case, but more experience might help.

**Comment by frivoal** [comment]
Yours are good questions. I'd add a couple:

* Separately from evaluating whether incubation is a useful thing (the consensus seems to be that it is), I'd like to see evidence for or against incubation **in a separate group** being a net positive.

I expect the answer to vary depending on the working group, with socially cohesive groups working on integrated technologies preferring internal incubation, while more loosely connected groups would care less either way or maybe prefer external incubation.

* Related to your second question: does WICG succeed in attracting a diverse range of participants. If not, do we still have the ability once the spec gets in the WG for i18n, a11y, and all sorts of diverse stakeholders to impact substantive changes to the spec to address their concerns, or are we already too constrained by implementation inertia and compat concerns?

My guess would be that the feedback received during incubation is deep, but fairly narrow, and that our ability to still meaningfully change things is limited by the time it takes to transition, and by the relatively high bar we still place to get things out of incubation, and that we should maybe be more accepting of failure even after starting on TR to compensate.

But this is gut feeling based, not evidence based, so I don't actually know.

**Comment by tantek** [comment]
I tend to agree with @frivoal's "gut feelings" here and lines of questioning. These questions about incubation are worth answering to demonstrate an improved explicit understanding of how to use incubation (whether it happens in WICG, another CG (e.g. SWICG), another WG, or outside W3C).

**Comment by dwsinger** [comment]
I'd kinda like to know whether we have a good definition of what a 'well incubated proposal' looks like, since it's the results/effects we want, not a specific place or way to achieve them. "Must be XXX Tall to Attack the YYY WG" -- what is XXX?

**Comment by paulbrucecotton** [comment]
>I'd kinda like to know whether we have a good definition of what a 'well incubated proposal' looks like

I am not sure what exactly you are looking for but you could start with these [Readiness Criteria](https://www.w3.org/Guide/standards-track/#criteria) which includes:

"The "empirical" criteria are inspired largely by the experience of some open source browser projects that use [an intent to implement process](https://docs.google.com/document/d/1vlTlsQKThwaX0-lj_iZbVTzyqY7LioqERU8DK3u3XjI/edit#) to build the case for shipping a new feature. This document refines this approach to apply to Recommendation Track transition decisions. The [Web Platform Incubator Community Group ](https://www.w3.org/community/wicg/)has adopted something similar [to determine when a spec under incubation is ready to propose to a Working Group](https://wicg.github.io/admin/intent-to-migrate.html). "

**Comment by dwsinger** [comment]
Yes, I had those in mind; I would mildly prefer that charters ask for the effect ("proposals are ready to be worked on in a working group; guidelines for what that means are at X, and incubation, for example in the WICG, is one way to get to that state") than say "incubate!"

**Comment by LJWatson** [comment]
The experiment is still in progress, and these are all good questions. Once we've been through the process (realised through the successful acceptance of this charter and the subsequent work in the WG), we'll be in a much better position to know some answers.

Meanwhile, there doesn't seem to be anything to change in the charter at present, since the status quo remains the same it was during our last two charter reviews.
