### ISSUE TITLE
WebPlat charter: Change WG name

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-html#149]
Feedback from the AC review:
The name should be changed to the Web Browser WG, because Web Platform implies a wider eco-system than the WG is actually working on.

**Comment by chaals** [comment]
I'd be happy to change the name, if there was an obvious alternative candidate that was notably better enough to justify the effort and the discussion.

The group does work that is not directed at browsers, and a lot of work at W3C outside the group is directed at browsers, so I don't think this is an improvement.

**Comment by jeffjaffe** [comment]
Core Web WG?

**Comment by chaals** [comment]
That illustrates why I think this discussion is fruitless. For some, the work on HTML and DOM is core, for others it is more or less irrelevant and the key is extending elements, for others the Web of data, or new capabilities for device interaction are the only really important bits of work on the Web. I'd be happy with "grab-bag C", which I think is somewhat more accurate, but we'd have to argue about why I propose "c", which brings me to my original position: That we close this issue without action.

**Comment by LJWatson** [comment]
With the chartered scope of the WG we're unlikely to find a name that adequately encompasses all we do (without being so long as to be unwieldy). We are likely to spend a lot of time discussing what name to give the bikeshed though, and I'm not sure there is enough impetus to make that a useful exercise.

**Comment by LJWatson** [comment]
We cannot change the name of the WG at this point in the rechartering process.
