### ISSUE TITLE
WebPlat charter: Scope is too broad

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-html#150]
Feedback from the AC review:
The scope of this WG is too large. The rationale for merging HTML into this WG is unclear. Transferring Service Workers and Background Sync into a new WG is a good start, but there should be further movement of work items into new WGs.

**Comment by chaals** [comment]
Yes, the scope of this group is unwieldy. There are three arguments in favour:

1. It has a large range of members, providing good IPR coverage, especially for specs where a very small group would be expected to join a Working Group dedicated to that spec. I believe this has been a basis for past objections to moving work out of the group.
2. It reduces the overhead of having to set up infrastructure, and relevant coordination, for multiple groups.
3. There are generally strong overlaps between people working on different specs in the scope.

One strong argument against the scope is that it deters some members from joining, as a direct consequence of the broad scope.

I don't think there is an ideal size - we essentially make an *ad hoc* decision about what to put together and what to split out based on pragmatic considerations. I actually think that's about the optimal approach.
