### ISSUE TITLE
WebPlat charter: Obtaining external IPR commitments

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-html#153]
Feedback from the AC review:
Is it clear how how an external IPR commitment is obtained? The charter should link to the form/mechanism used for this purpose.

Currently this is mentioned in the Communication section. It should be moved into its own section, because it isn't really about communication.

**Comment by chaals** [comment]
The "standard current procedure" is complicated and *ad hoc*, and an alternative is more often used. It would be good to have a proper procedure to link to. @wseltzer 

In the case that this becomes reality, agreed that it doesn't need to be listed as communication.

**Comment by wseltzer** [comment]
We're working to address this globally. Recommend rejecting the specific feedback here.
