### ISSUE TITLE
WebPlat charter: Define "distinct browser engine project"

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-html#154]
Feedback from AC review:
Do we understand what is meant by "distinct browser engine project" (from section 2.1)? Perhaps a parenthetical after "distinct" to clarify that it means separately managed projects even if they have a shared ancestory?

**Comment by chaals** [comment]
I believe I understand the meaning of "distinct", and I understand various ways to determine whether two "browser engine projects" are "distinct", and what is a "browser engine project" as opposed to a "brower project" that isn't related to the engine.

I suspect that focusing the definition through one clarification invites further attempts, leading us to an unproductive but costly effort to describe something which is in any event merely noting that we should keep an eye on the Working Group's relevance to reality - the same point underlying e.g. #146 and #147.

I propose we close this issue without action.
