### ISSUE TITLE
Clarify the problem space

### ISSUE THREAD

**Issue by AFBarstow** [w3c/charter-html#18]
I think the document is lacking some context re the problem space the proposal is supposed to address and that makes it challenging for the broad set of stakeholders to evaluate the proposal. More specifically, here's what I said on a W3C Member confidential list and it captures the gist of the issue:

[[
https://lists.w3.org/Archives/Member/w3c-ac-forum/2015AprJun/0188.html

Perhaps part of the problem is there isn't broad consensus on "what's 
actually broken"? The draft [Plan] is a bit short on the problem space 
and focuses mostly on aspects of implementing the proposal. I note 
Philippe's [Slides] include some information about the problem space and 
others (for example [_4 names and links to their comments were deleted_]) 
provided their opinions.

It's good to see a desire to make priorities, etc. "data driven". As 
such, has the HTMLWG done a broad "postmortem" survey/analysis to help 
identify: those things that worked well, the problem areas, things to 
differently, etc.? It seems like we would want feedback not just from 
all of the WG participants and consortium members but also the numerous 
other stakeholders such as content providers, application developers, 
implementers, etc. (I apologize if missed this analysis, but please do 
send me the URL.)

Re the question about how to "structure/organization" follow-on work - 
in a healthy organization, structure is an implementation detail that 
follows from a clear and agreed strategy and vision. Is there broad 
agreement on the strategy/vision for the evolution of the HTML standard? 
If yes, please let me know where I can find it (and please don't say 
"see application foundations" because those are simply "the new activity 
buckets")? If not, discussions about how to "structure" follow-on 
HTML.NG work is premature.

[Plan] http://w3c.github.io/charter-html/html-plan.html
[Slides] http://www.w3.org/2015/Talks/0506-html/
]]

**Comment by adrianba** [comment]
I wrote up some of the problems we see here: http://github.adrianba.net/webstandards/HTML-innovation-vs-maintenance
