### ISSUE TITLE
Bugs get property triaged, prioritized, and addressed

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-html#2]
How can the Chairs can ensure that bug triage get done property?

**Comment by plehegar** [comment]
Added a section on data-driven focus.

**Comment by rubys** [comment]
I respectfully disagree that this item is addressed.  The root problem is that the browser vendors are not participating.  It makes no sense for the chairs to prioritize without browser input.  My URL work is a counter-example to the premise that a "data-driven focus" is sufficient.  XHTML2 is an example of what a WG without browser input produces.

**Comment by chaals** [comment]
Getting work done properly is a question of doing work. Nothing in a charter makes that happen, and only an egregious requirement stops it happening.
