### ISSUE TITLE
Who makes request to transition?

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-html#20]
[[
Proposal editors will prepare a "request to transition" assessment
]]
Shouldn't we allow anyone to make such assessment, not just the proposal editors?

**Comment by darobin** [comment]
+1

**Comment by adrianba** [comment]
Sure, but it is important that the editors of a proposal agree so we don't have two parallel workstreams. Of course, this is just a request and ultimately the WG (and likely AC) have to agree. I think it will be a common case for the editors to make the request but it doesn't need to be a requirement.

**Comment by marcoscaceres** [comment]
Agree - anyone could prepare the request. It seems unlikely that an Editor(s) wouldn't be involved or that the chair wouldn't be consulted before any transition would happen (even if not spelled out as part of the process).

**Comment by LJWatson** [comment]
@marcoscaceres

Perhaps it should say something to the effect that a transition statement can/should be prepared by anyone with reasonable knowledge of the proposed specification, but that it should be presented for review/consideration by the editor(s)? Just thinking there should be some light formality to submitting a transition statement for review…

**Comment by marcoscaceres** [comment]
@LjWatson, yes, agree. Maybe just "demonstrated consultation and consensus within the CG".

**Comment by LJWatson** [comment]
@marcoscaceres
That works for me.

**Comment by darobin** [comment]
I like "demonstrated consultation and consensus within the CG". This shouldn't require approval from the editor. Sometimes they go do something else and aren't heard from in a long while, sometimes they become crazy... you never know. Obviously I would expect the CG to make sure that an editor's voice is heard if s/he doesn't want to transition, but we shouldn't block on individuals, ever.

**Comment by plehegar** [comment]
+1

**Comment by wayneca** [comment]
The current text makes it look like specs always move to WGs at the request of the CG.  What about if the W3C thinks a spec is ready for standardization.  I assume a W3C can choose to include any of the CG specs in a WG charter at any time it chooses (as another CG could also fork it).  The charter should make that clear and not have it look like transition is always initiated by the CG.

Also, "It is the role of the Working Group to evaluate such assessment before starting a standardisation effort."  Could be a WG adding a deliverable and rechartering to get approval or it could be formation of a new WG.  It's W3C evaluating it, not necessarily an existing WG.

**Comment by adrianba** [comment]
I was about to make a similar comment to @wcarr. It needs to be clear that this is a **request** to transition and a working group needs to accept such a request in order to proceed.

**Comment by wayneca** [comment]
but, couldn't a working group decide to take a CG spec without any transition request too?  That's what I think needs to be clear.   Anyone can fork a spec, including a CG.

It's also not always a WG that decides.  There could be no WG and what happens is a Charter gets written and sent to the AC to create a WG or a charter gets revised and sent to the AC.  So, it isn't just a WG deciding unless the spec is already a deliverable.

**Comment by plehegar** [comment]
The CG does not have veto power over the Working Group if the WG wishes to take up an idea. The CG cannot force a Working Group to take up a work item item. Yet, it would be imho harmful to the WG to take an idea up with no support from the CG. At the end, it's a balance between the WG, who wishes to standardize the idea, and the main contributors of the idea. The role of the CG and WG chairs and W3C team is to facilitate this balance, and ensure we have continuity in the community if we do the transition.

**Comment by adrianba** [comment]
Most of the time it is going to be the same people involved on both sides.

**Comment by plehegar** [comment]
I figured the CG Chairs should be savvy enough to give proper recommendation to the individual.
So how about the following:
[[
Individuals, after consultation with the Chairs, may prepare a "request to transition" assessment, outlining use cases, as well as implementation considerations, security, privacy, accessibility, and internationalisation impacts. Those requests are evaluated within the Community Group as well the targeted W3C Working Group, if any. The role of the CG and WG Chairs and W3C team is to facilitate the migration and ensure proper continuity in the community who proposed the idea.
]]

**Comment by adrianba** [comment]
LGTM.

**Comment by marcoscaceres** [comment]
Agree, looks good.
