### ISSUE TITLE
[CG Charter] Decision process must be fair, not editor owns the spec

### ISSUE THREAD

**Issue by wayneca** [w3c/charter-html#21]
"If substantial disagreement remains (e.g. the group is divided), the editors will continue with their preference. ".  The editor(s) disagreeing with the rest of the group could be "substantial disagreement" or a few friends of the editor challenging anything the editor does not like.  The remedy offered is: "In extreme cases, someone may choose to fork the spec into a new GitHub repo and move forward with alternative text. "  That is meaningless if the Editors are several of the 4 primary Web Browser vendors.  You can't simply go off elsewhere without them.  The group needs to be able to make decisions where there is rough consensus and there needs to be a way to ensure that editor's reflect the will of the group.  (rough consensus doesn't mean unanimity, but it does mean the editor cannot override the dominant view of the group).  At the least, the charter should say the editor cannot decide in opposition to the rough consensus of the group and create a way to have a poll or CfC.  

The W3C CG optional charter template provides for a vote when disputes cannot be resolved.  That is used in several important CGs and has never been needed because there is a fallback to ensure the editor respects the dominant view.  

For a key decision where progress cannot be made without the decision and where a poll shows no dominant view, the editor in consultation with the Chair could decide that by choosing an option with at least some significant support.

In a typical CG, its fine to not have a charter or to not have fairness because people can fork.  It's different if its the single Web Platform CG started by W3C itself with the idea that it would be a primary place for incubation for specs headed for WGs.  it should be clear that Editor's don't own the spec and that they must reflect the dominant desire of the group and not just do whatever they like any time there is disagreement.

**Comment by rubys** [comment]
From my point of view, I would suggest that the proposal above is a premature optimization.  The expectation isn't that everything will survive incubation.

As an alternative, I would suggest that the [request to transition](http://w3c.github.io/charter-html/request-to-transition.html) be extended to include four sections motivated by the existing [transition request](http://www.w3.org/2005/08/01-transitions.html#reqs-satisfied) which are informative only (aside: the similarity in names makes this confusing!):
- Status of the document with respect to the group's requirements
- Status of the document with respect to other group's dependencies
- Status of the document with respect to wide review
- Status of the document with respect to open issues

As a part of the acceptance of the document by the Working Group, the chairs should evaluate editor candidates based on a number of criteria.  One of those criteria should be a willingness to reflect the consensus of the group.

**Comment by adrianba** [comment]
> In a typical CG, its fine to not have a charter or to not have fairness because people can fork.
> It's different if its the single Web Platform CG started by W3C itself with the idea that it would
> be a primary place for incubation for specs headed for WGs. it should be clear that Editor's don't
> own the spec and that they must reflect the dominant desire of the group and not just do
> whatever they like any time there is disagreement.

I spent a fair amount of time thinking about this before proposing something different. My proposed charter was based on the CG template but I deliberately departed here.

The goal of the incubator group is to let all the flowers bloom. Some won't bloom though and will wither and die. Participants should be encouraged to work together to achieve consensus to the greatest extent possible. I think during incubation it is perfectly reasonable for an editor to own their proposal. Ultimately they will only be successful if they are able to reflect enough consensus for a proposal to move forward and transition to a WG. If they "just do whatever they like any time there is disagreement" then they probably won't be successful. However, reasonable people can fundamentally disagree on technical decisions and it should be fine for people to fork in that situation and proceed with alternatives for a while. Hopefully people can find a way to merge them back together or perhaps one way will not prove viable.

One a spec makes it into a WG then all the usual process rules apply. I agree with Sam that chairs' choice of editors in a WG includes considering their ability to reflect consensus in the document.

The risk of insisting that editors don't own their proposals in the CG is that we'll just push them out of the CG back on to personal repos and we'll lose the other benefits of the CG (primarily traceability of contributions).

**Comment by darobin** [comment]
I think there are subtleties to spec ownership that need to be surfaced so that we can agree.

I think that editors should have full ownership of their incubating spec, with the understanding that it is completely fair game for whoever disagrees with their decisions to fork it. The group needs to be able to handle having multiple parallel competing version of essentially the same spec developed in parallel as a _success_ mode. People who disagree with something should be _strongly_ encouraged to take ownership of their objection by taking ownership of an alternative fork. I don't think this should be limited to extreme cases. It's open standards, go fork and multiply!

The social dynamic here is that the group of editors most adept at negotiating merges amongst themselves is likely to come out on top at the end. (Hopefully because they've worked out something better, too.)

There is, however, a point at which ownership needs to transition from an individual (or group thereof) to a collective: around the time at which it moves to a WG. This needs to be spelled out well so that people aren't surprised.

Hopefully this won't happen (but you never know what kind of crazy situation a group can end up in) but it should be possible for the group to decide to move a spec to a WG without the editor's consent. It is in effect equivalent to the group forking the document.

**Comment by stevefaulkner** [comment]
On 22 May 2015 at 09:43, Robin Berjon notifications@github.com wrote:

> I think that editors should have full ownership of their incubating spec,
> with the understanding that it is completely fair game for whoever
> disagrees with their decisions to fork it.

+1

## 

Regards

SteveF

**Comment by adrianba** [comment]
> People who disagree with something should be strongly encouraged to take
> ownership of their objection by taking ownership of an alternative fork. I don't
> think this should be limited to extreme cases.

@darobin, I agree with you. This should be an expected work mode while still encouraging discussion first. It should be clear that people are expected to at least try to work out their differences before reaching for the fork. That said, pull requests are great ways to make positions concrete and should be encouraged above all else. It is easy to write a negative comment. It requires more effort to make a positive change proposal with spec language.

Speaking of which, I will try to come up with some clarifying language for this today and make a PR.

**Comment by wayneca** [comment]
People are thinking of this working in a particular way as being about early ideas and early incubation and people from outside W3C.  When things get reasonably solid the good ideas move to WGs.  So it doesn't matter how its developed.  

However, the choice could be made to develop the spec in this CG until it is in wide use and is widely implemented.  e.g. the Speech API is still in a CG.  It could be some specs are very settled before moving or never move but become part of the Web platform.  It could be they allow a WG to comment, but not change the spec.  I'm not suggesting that's a good thing, but it could happen if for some spec implementers preferred doing it in this CG.  This CG doesn't prevent that model of development.

This CG isn't just people outside W3C experimenting with something.  It likely would be that inside the WG, anything suggested first goes to this CG, so it becomes how specs start and replace what now is often done inside WGs.

The idea of preference in transition for "nice" editors fixes this I think is not practical at all.  Obviously, The way Service Workers was developed was fine - it's a great spec and very important. If that had been developed in an absolutely awful way, that in no way would slow transition to a WG.  It would likely be used as evidence it should transition!  So, the idea transition preference fixes doesn't work.  When it gets to transition, it should just be whether its useful and reasonably well enough along for the WG to take it.  I don't think we should overspecify that and it definitely doesn't fix the fairness issue.

Perhaps, the charter could say that when a spec reaches the stage beyond very early incubation that the expectation is that the editor's decision will reflect the rough concensus of the group and that where there is dissent a decision has support of a substantial portion of the group.  (so not the whole group on one side and the editor chooses something else).

**Comment by rubys** [comment]
> with the understanding that it is completely fair game for whoever disagrees with their decisions to fork it

How do we establish and maintain that understanding?  I'll note that there is a vocal set of people who feel that forking of living standards is a bad thing.  How do we resolve this?

**Comment by wayneca** [comment]
Here is suggested wording:
[[
Once a proposed spec is beyond early incubation, the Editor(s) must respect the rough consensus of the group in making decisions.  Where there is dissent and rough consensus has not been achieved and a decision is needed, the Editor[s) may choose a path forward, but that decision must have substantial support in the group.  The Editor(s) cannot use the fact of lack of agreement to force a path without considerable support in the group.  Decisions without rough consensus are recorded as such.  The Chair determines when a specification is far enough along for this to apply.
]]

**Comment by adrianba** [comment]
> I'll note that there is a vocal set of people who feel that forking of living standards is a bad thing.

@rubys In my view, the goal of this CG is to incubate new ideas but not turn them into some kind of "living standard". Once something reaches a good level of maturity we want to encourage transition onto a standards track in a working group. If we set the expectation at the outset that someone may take your idea, fork it, and try to run with it in a different direction then can we avoid this being a surprise?

**Comment by adrianba** [comment]
> The way Service Workers was developed was fine - it's a great spec and very important. If that had been developed in an absolutely awful way, that in no way would slow transition to a WG.

@wcarr, I don't know if you can make this assertion. I don't know what would have happened if this had been developed a different way. Alex was clear from the start that he wanted to write a spec and hopefully bring it into the W3C. 

Is there a good example of something being developed in a CG in a bad way that is widely implemented and that people don't like? I don't think the Speech API counts - as far as I recall there wasn't sufficient interest from people to join a working group to do that work when one was offered. According to [caniuse](http://caniuse.com/#search=speech), it is only in WebKit/Blink based browsers based on common history.

**Comment by rubys** [comment]
> Is there a good example of something being developed in a CG in a bad way that is widely implemented and that people don't like?

I'm not sure what you are looking for, but perhaps the Microdata API qualifies?  Once widely (but not universally) implemented, later removed from a number of implementations.  See https://bugzilla.mozilla.org/show_bug.cgi?id=909633 for some links.

**Comment by adrianba** [comment]
> I'm not sure what you are looking for

I'm trying to understand why @wcarr is concerned about letting editors determine the level of consensus they want to achieve during incubation. My assertion is that successful projects will require a fair degree of compromise and consensus building. @wcarr wants chairs to require editors to document the consensus even if they personally disagree. I'm wondering if there are examples of things that cause this concern. @wcarr cited Speech API but I'm not sure that counts.

**Comment by silviapfeiffer** [comment]
We already have a lack of good editors. The more bureaucracy you put around
editing, the less people you will get to volunteer for the job. We should
not make it harder for editors to get stuff done. Getting things done
unfortunately sometimes requires making decisions that need to be revised,
but there is no other way forward.

Best Regards,
Silvia.

**Comment by rubys** [comment]
>  @wcarr wants chairs to require editors to document the consensus even if they personally disagree. I'm wondering if there are examples of things that cause this concern. 

The closest I can recall is the ping attribute, where Ian didn't update the CG copy to match:

https://lists.w3.org/Archives/Public/public-html/2010Mar/0132.html

I don't believe that this is a pervasive problem.  I continue to believe that it shouldn't be enforced at the CG level by anything other than condoning forking.  I believe that it should be addressed at the WG level by careful selection of editors.

**Comment by adrianba** [comment]
> I don't believe that this is a pervasive problem. I continue to believe that it shouldn't be enforced at the CG level by anything other than condoning forking. I believe that it should be addressed at the WG level by careful selection of editors.

+1

**Comment by plehegar** [comment]
I agree with @rubys here. If the document becomes important enough that the editor needs to start abiding to a consensus, it's one of the signs that the document should be migrated into a Working Group. You get the choice of forking or getting support to migrate the proposal into a Working Group. Doing otherwise would be counter-productive to the intent of the CG imho.

**Comment by wayneca** [comment]
> I agree with @rubys here. If the document becomes important enough
> that the editor needs to start abiding to a consensus, it's one of the signs 
> that the document should be migrated into a Working Group. 

What if they don't want to migrate to a WG because they don't like the "bureaucracy" or the major implementers can't agree on what WG, e.g. some insist on WebApps(because everyone is in that), some insist it not be WebApps(because they're in WebApps and don't want to license that spec).  So it stays where it is in the CG while that goes undecided.  The Charter doesn't do anything to make it so specs have to leave the CG at any point (and shouldn't), so it could be some specs stay in the CG until they're widely implemented.

This CG charter being proposed appears to allow WHATWG style decision making.  Very, very good specs have been created in the WHATWG.  But, that doesn't mean everyone would want W3C to switch to those rules.  Some mild statement about decisions needing to reflect some level of group support  (only for specs that are considered important) is what I was looking for - like 98% to 2%, the 2% doesn't win if the spec is getting serious attention and input.

**Comment by rubys** [comment]
> What if...

I don't think the worse case scenarios are likely given the F2F meetings.  I think it is important that the F2F meetings be allowed to discuss and resolve these issues.  That's why I don't believe that the F2F meetings should be removed from the plan.

I just don't believe that regular meetings with agenda (and now, apparently, minutes) including the four largest browser vendors and the W3C team covering topics like these can be reasonably considered "side" meetings.

**Comment by wayneca** [comment]
Getting back to the sentence this is about:

> If substantial disagreement remains (e.g. the group is divided), the editors 
> will continue with their preference. 

Since part of this proposal is the idea that many committers will replace the role of one or two very powerful editors, how about:

> If substantial disagreement remains (e.g. the group is divided), the repository committers
> will select a way forward that had considerable support. 

The "Editor" could be the sole committer and then you have the Editor chooses.  But, the wording doesn't prevent switching to a model where committers earn a position of trust through their contributions.

**Comment by wayneca** [comment]
this is fixed and should be closed
