### ISSUE TITLE
Migrating back from a WG to a CG

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-html#23]
How to transition back from the WG IPR policy to the CG IPR policy if specs turn out not to be ready for the standards track but are not “abandoned”?

**Comment by rubys** [comment]
> How to transition back from the WG IPR policy to the CG IPR policy if specs turn out not to be ready for the standards track but are not “abandoned”?

This seems to be presuming that work stops in the CG once a transition occurs?  I think that's unwise and not accurate.  If you feel differently, please make that assumption explicit in the plan.

I will note that that has traditionally NOT been the case with the WHATCG.  

I will also note that making this a requirement would be messy.  In the CG, the emerging consensus is that forks are condoned.  If one such fork transitions, does that mean that the CG is obligated to cease work on all other forks?

I also would hope that a transition of, say, Canvas 2D Context, Level 2, would not impact ongoing work on Canvas 2D Context, Level 3.

**Comment by plehegar** [comment]
I agree that we cannot make the requirement to stop work in the CG. I didn't presume that the work would stop in the CG but there will be such instances however. Or what if 2D L3 gets done within the WG and it turns out it would be better continued in the CG instead? If you make a contribution into the WG and the spec doesn't go to REC, all bets are off.

**Comment by rubys** [comment]
It seems that we are in sync.  "transitioning back" is merely a point in a spectrum.  What needs to be made clear is that migration does not mean that work necessarily stops in the CG.  That being said, should work happen to stop in the CG, it can restart in the CG at any time.  That time could occur while work is occurring in the WG, at the time that work stops in the WG, or even at a later point.

**Comment by wayneca** [comment]
>  If you make a contribution into the WG and the spec doesn't go to REC, all bets are off.

I thought the point being made was contributions made in the WG only cause licensing at REC.  So, if you move a spec from a WG to a CG, the parts contributed in the WG don't have any patent licensing associated with them in the CG (only the parts contributed in the CG do). If you never go back to the WG, you lose the licensing you would have gotten from the WG for the parts from the WG.  

But, that's the same as the WG abandoning the spec and that happens now.  That's what the WG would be doing if they sent it back to the CG and never took it back.

If it does go back to the WG and finish, it doesn't seem like it would matter whether it went back and forth to the CG or not.
