### ISSUE TITLE
[transition] Compatibility Risk paragraph isn't clear (editing problem)

### ISSUE THREAD

**Issue by wayneca** [w3c/charter-html#24]
> Compatibility Risk
> Please characterize how much we might regret standardizing this new feature 
> were we might to change or remove it in the future. If you don’t have a github 
> repository, include in this email links to relevant discussions, or documentation 
> about support for the feature on the Web.

There's something wrong with the first sentence (editing problem).  I think it's asking if it is too early to standardize the feature,  It looks like it's also asking how much discussion and support there has been on the feature.  That seems a separate topic, so maybe a different section.

**Comment by wayneca** [comment]
I see what it's saying now.  it's a typo - extra word "might"

Would be better as: "Please characterize how much we might regret standardizing this new feature as proposed were we to change or remove it in the future."

**Comment by plehegar** [comment]
Fixed
