### ISSUE TITLE
[charter] over time the CG will include people who have signed CLA?

### ISSUE THREAD

**Issue by wayneca** [w3c/charter-html#25]
> Over time, the WPI CG will grow to include all the people that have signed up 
> for their contributions to be made according to the W3C CG CLA, much like an 
> open source project grows a list of contributors making pull requests under the
>  project license.

Typically, in a CG you agree to the CLA and if it isn't a W3C AC rep doing the agreeing, W3C staff checks out the employer affiliation part (e.g. if their employer agrees to a commitment or if they don't list an employer should they have.) and if it checks out they're in the CG.  Does this sentence mean there is some other additional step or is it saying that usual check isn't taken automatically?  What is it that happens "over time"?   It should be explicit how someone joins the CG.

**Comment by plehegar** [comment]
That paragraph is simply indicating the direction on how the community will evolve while having proper IP commitments. Some folks will make contributions without being part of the CG and will need to be sorted out. It's BAU as far as I know and the text didn't mean to add extra steps.
We don't need to be explicit on how one joins a Group in a WG charter. Not convinced we need to be explicit for CGs either.

**Comment by wayneca** [comment]
I wasn't suggesting you repeat how people join groups where it is specified elsewhere.  The wording seems like:
1. People enter into the W3C CG Community Licensing Agreement for the WPI CG.
2. They are not in the WPI CG, but at some future (unspecified) time the CG will grow to include them.  

> Over time, the WPI CG will grow to include all the people that have signed up for their 
> contributions to be made according to the W3C CG CLA, much like an 
> open source project grows a list of contributors making pull requests 
> under the project license.

Is the following the same as what you intend?

> The WPI CG includes all the people who have agreed for their 
> contributions to be made according to the W3C CG CLA, much like an 
> open source project grows a list of contributors making pull requests 
> under the project license.

**Comment by plehegar** [comment]
Note that the latest additional on this front:
 http://w3c.github.io/charter-html/incubator-cg-charter.html#process
