### ISSUE TITLE
[charter] how is a new Specification started in the CG?

### ISSUE THREAD

**Issue by wayneca** [w3c/charter-html#27]
How does someone start a new Specification in the CG?  (W3C CG CLA is about Contributions to CG Specifications.  A key thing about CGs is how they decide to work on Specifications) 

The Charter seems to be using the term "proposal" as a synonym for a things that are being developed in the CG and that will eventually be proposed somewhere else.  I don't see anything about "proposals" to undertake work in the CG itself. 

Can anyone start a new Specification?  Does the CG decide anything about that?  Or is it more automatic like creating a CG, where it is automatic if it meets minimal requirements?  However it starts, is there any way to terminate it?

**Comment by marcoscaceres** [comment]
Generally, people should be free to spin up a repo, or just a markup file, for a new spec if they want - the CG leads will guide that (e.g., push people to show there is a need). ~90% of the new specs will die on the vine, which is fine. Of the specs that die, some will come back to life at a later time. I don't think we need any special wording here on the process.

**Comment by wayneca** [comment]
Who are the CG leads that decide this?  It's apparently not the CG Chairs.  The Editors own the specs and some other unspecified group of CG Leads decide which new specs are adopted?

When companies are making decisions about whether to join this CG or not and are wondering about how it is run, what is it they're supposed to look at?

**Comment by marcoscaceres** [comment]
> When companies are making decisions about whether to join this CG or not and are wondering about how it is run, what is it they're supposed to look at?

I get the sense there might be some other underlying question/issue you are not articulating? Are your concerns more based on IPR? The processes for spec development are organic and likely cannot be nailed down  _a priori_ (nor should they be restrictive, to allow organic experimentation and evolution of features - as well as for the ability for things to fail fast). How the work is done doesn't really matter, so long as those that contribute understand the implications of what they are contributing. 

So, let's flip this: what would you (or those "wondering about how it is run") expect to see in the charter re: specification development process? What would make, for example, Intel comfortable with joining this kind of CG?

**Comment by wayneca** [comment]
> I get the sense there might be some other underlying question/issue you are not articulating?

not intentionally :)  If there's an underlying issue, it's that I'd like to be able to tell my company how basic things about this new proposal work.  

This CG is about being able to do incubator work in the form of CG Specifications (because that's what the CLA applies to, CG Specifications).  

How does one get work started on a new CG Specification?  

From what you were saying about CG Leads, there is some sort of process, but not in the Charter.

**Comment by marcoscaceres** [comment]
> How does one get work started on a new CG Specification? 

It really depends - it's not straight forward. For example, after discussion on (twitter/blog/teleconf/hangout/mailing list/[other social thing]) we would create a repository on GH. We would then start throwing strawman proposals in to see what sticks. 

For instance, to get to:
https://github.com/whatwg/mediasession

After some discussions with people from Opera, we posted a rough proposal or what we wanted to achieve:
https://github.com/whatwg/mediasession/commit/d40eda52ff009af7acdaa36b1b24823cec906d73

Opera posted a proposal in their own space:
https://github.com/richtr/html-media-focus

On twitter, a bunch of us reached out to people from SoundCloud, and other companies. to see if they were interested. They posted a bunch of feedback on GitHub and on Twitter. These companies confirmed that this would be useful to them, and would likely use this technology.  

Mozilla posted a counter proposal: 
https://github.com/whatwg/mediasession/blob/master/MediaRemoteControl.md

Opera then refined theirs and proposed something different. Google countered with an alternative (but in the github issues, iirc). We then had a call with Apple, who had a different opinion - which changed everyone's thinking. From that call we drafted:

https://mediasession.spec.whatwg.org/

And now have a living spec.  

If you mean "but how do you even propose a spec?", then that is driven by market need normally. Use cases bubble up naturally - e.g., developers start running into issues, like they did with responsive images. Or there is a clear problem: "I can't pause my music in the browser", hence "media session API" . 

So, the process is really about reaching out to people in an unstructured way. Eventually, some words end up on a repository somewhere - and then it takes a lot of "shopping it around", on social media - on small teleconfs - on large mailing lists - etc etc. Whatever is needed to get the thing to actually take off - and to get people excited about it (or get an early implementation, as Google did very successfully with both Service Workers and Web Manifest). Again, most things will fail - but some will survive with enough implementer interest that they will become things that are worth implementing.  

The process should acknowledge that getting that initial spec up and running can be extremely unstructured and messy.  See also: https://wiki.mozilla.org/WebAPI/DesignGuidelines

**Comment by wayneca** [comment]
So someone proposes what Opera did and says they want to work on a spec in that area and says they'd like to solicit ideas for how to proceed.  however, it gets decided, the CG gives them a github repository.  lots of people post things to it. in the middle of that, someone could get a different repository to work on some other variant.  and in the end both of them could wind up with mediasession and get a repository for that.

So, what's the problem with having some way to ask for a repository or to add a directory in a repository?

the process could be like starting a CG -- 5 people say they agree and it happens -- and if the CG has a whole regrets some bad thing happening they can reverse it in extreme situations.  Or it could be some quick poll.  or it could be the chair knows they should approve reasonable requests and the CG can back those out.  just something written down

**Comment by darobin** [comment]
I think it's fair to write down how a spec gets started, even if the answer is no longer than "You set up a GH repo and tell the CG about it." Just because it's simple doesn't mean it shouldn't be documented — especially as we try to bring newcomers in. A lot of developers are scared of standards; standards have a reputation for being complicated. If things are simple, we should point it out!

Incidentally, I happen to think that we ought to have a little "process", but that it should be 95% automated. The reason for this is because we actually want an "official" list of which repositories are considered to be under the CG's umbrella. This allows us to have the hooks that can do things like check that contributors to a PR are in the CG/IPR-ok. By automating it we can immediately generate proper `LICENSE`, `CONTRIBUTE.md` file. And generate a default spec template. And set the repo up with WebSpecs. There are quite a few good sides to this :)

All of this to say: I think we should indeed document how you start a spec in the CG. I think it should be along the lines of "You go fill out that form over there, and you'll be good to go".

**Comment by wayneca** [comment]
By "You set up a GH repo" I assume you mean you cause W3C to set one up in W3C's account?

Since there are standard LICENSE and CONTRIBUTING files for the rep (as I understand what's intended), the repo's either need to be where W3C can control those files or there needs to be a requirement in the Charter.

I agree there shouldn't be a lot of process, but the Charter should have any guarantees that participants can count on (that are not already in the W3C Community Process (like the things I've been asking for) or key things about how it works like how you set up a new spec to work on.  It doesn't need to say exactly how its done (like not you fill out a form here ...).  

Suggestion: 
"Starting new work in the WebPlatform CG.  Anyone can request a repository for new work in this CG by providing a name for the repository and a description of what the repository is for (please see the Web Platform CG Web page for details).  The expectation is these will be approved, but they may be rejected (or later halted) by the Chair if it is out of Scope for this Community Group or "is likely to cause offense or confusion, is frivolous, or is overly broad".  Those are the same rules that would prevent starting a Community Group.  This decision by the Chair can be reversed by a decision of the group."

**Comment by marcoscaceres** [comment]
> By "You set up a GH repo" I assume you mean you cause W3C to set one up in W3C's account?

I don't think that should be a hard requirement, but very much encouraged (for various good reasons). However, we have Service Workers living in Alex's repo today, and we have WebIDL living in Cameron's repo. They both refused to move their spec to the W3C space. I think that is fine, however. 

> Since there are standard LICENSE and CONTRIBUTING files for the rep (as I understand what's intended), the repo's either need to be where W3C can control those files or there needs to be a requirement in the Charter.

The requirement is really just that those files be present. For instance, you don't need to host your stuff at MIT to have an MIT license.

**Comment by wayneca** [comment]
I thought there were particular LICENSE and CONTRIBUTING files being developed, so they would be uniform across specs.

Is the idea for this CG:
-- the scope is anything in the Web Platform (including Web Browsers, other UAs or servers, like WebApps -- anything that could be in any application that does anything or the server support needed for that)
-- licenses and how contributions are made are whatever the Editor of that spec chooses.  They all, however, have the CLA apply to specifications in addition to whatever other licenses are required.

Could some particular CONTRIBUTING file in some repository outside W3C says any comment made on some list like the WHATWG list or anywhere on discuss.webplatform.org is a contribution to the CG covered by the CLA (in addition to whatever other licenses are in the LICENSE file)?

**Comment by marcoscaceres** [comment]
> I thought there were particular LICENSE and CONTRIBUTING files being developed, so they would be uniform across specs.

Correct.

> -- the scope is anything in the Web Platform (including Web Browsers, other UAs or servers, like WebApps...

Yes. 

> -- licenses and how contributions are made are whatever the Editor of that spec chooses

Re: licenses - No. They should have to use the W3C one. How contributions are made can be problematic, but we should encourage contributions to be made in a format that is publicly archived - i.e., added to the Wiki of the project or even as just a bug in the issue tracker for the project.  

> Could some particular CONTRIBUTING file in some repository outside W3C says any comment made on some list like the WHATWG list or anywhere on discuss.webplatform.org is a contribution to the CG covered by the CLA (in addition to whatever other licenses are in the LICENSE file)? 

It could, but it might be problematic. IANAL, I don't think you can automatically subsume contributions from mailing lists without the sender explicitly acknowledging that that is happening (GitHub makes this easy, but other forums probably won't - like if a group of us bash something out in an Etherpad over IRC, which I've done quite a few times). This is why people are then forced to sign the CLA - to make it explicit that all their previous contributions to the list are covered.

**Comment by wayneca** [comment]
> > I thought there were particular LICENSE and CONTRIBUTING files being developed,
> >  so they would be uniform across specs.
> > Correct.

Good!

> How contributions are made can be problematic, but we should encourage 
> contributions to be made in a format that is publicly archived - i.e., added to 
> the Wiki of the project or even as just a bug in the issue tracker for the project.

It should be specific and in the CONTRIBUTING file so that contribution tracking can be automated.  

How it could work: GitHub username associated with each W3C user account (W3C should do that for all CGs, WGs. This CG could require using GitHub repositories for all specs.  And could say contributions are made in GitHub Issues and pull requests.  And require specifying contributors using a particular format for listing GitHub usernames of people making that contribution in the comment in the pull request and the commit.   

Benefits from doing that:
1. automatically know if contributor has signed the CLA, and hold up the pull request until they have. 
2. if the CG has a huge number of participants (thousands), can prioritize processing the CLA to people who make contributions (If a participant isn't a W3C Member, W3C staff has to check if that person's employer needs to make a commitment or not).  So, 5 people are listed as contributors in a pull request and if some of them have agreed to the CLA but it wasn't processed yet, that moves up in the queue.
3. automatically tell people they're listed as a contributor in some particular pull request or commit for some particular spec.
4. automatically indicate what specs a company has contributed to.  (to help them be aware of where they are making patent licensing commitments).

If you have to read Issues and WiKis and mail lists, etc., to determine who made contributions, there's no way to automate any of that.  It could be it happened at lunch somewhere, but the formal contribution would be recorded in an Issue or pull request listing who is contributing it - and that would be the Contribution.  That leaves flexibility for how to have discussions, while it is specific about where the resulting contribution is made and who made it.

**Comment by marcoscaceres** [comment]
> 1. automatically know if contributor has signed the CLA, and hold up the pull request until they have.

Why not just say in CONTRIBUTING.md that by doing a PR you are signing the CLA? That makes the rest of the steps not needed.

**Comment by darobin** [comment]
By "creating a repo" I absolutely don't mean that W3C would be involved. We want people to come with all sorts of stuff that we don't want to have to decide whether we endorse or not. We don't want to have to manually set anything up.

The plan is that you get a Web interface that can create a repo with the right files and configuration (or add that to an existing one), under any account or organisation that you have write access to. Your repo then becomes monitored for contributions, and you can publish to https://spec.webplatform.org/ (or whatever publishing location we use in its stead).

The UI would indicate that we reserve the right to drop repos if they don't match some criteria. But this needs tooling, not process!

We could also regularly validate that our roster of repos is playing by the rules.

**Comment by adrianba** [comment]
Actually I think there does need to be some structure here. One of the key goals for creating the CG is to have a one-stop agreement for the CLA. If you are in the CG then you automatically have signed up to the CG contribution agreement for all repos that are under the auspices of the CG. And they all have the W3C CG contribution license. This is part of reducing the friction of starting new work while having known contribution history.

Without this we're no better off than creating a new CG for each proposal. So the goal is not to have a new custom CONTRIBUTING.md for each repo.

Secondly, I want to have tooling that allows us to track what contributions have been made into CG repos. This means having an index of the repos that contain proposals for the CG. My preference is that these are in one organization to make finding them easier rather than being scattered across random people's personal repos.

Thirdly, I would like to be able to have tooling that understands the GitHub ID of CG participants. This way we can periodically crawl the contributions into CG repos and make sure that people have signed up to the CG.

**Comment by silviapfeiffer** [comment]
I must admit I was somewhat surprised that the setup of a CG contained
WordPress, a wiki, mailing lists, but not a github repo.

Best Regards,
Silvia.

**Comment by plehegar** [comment]
@silviapfeiffer the CG/BG were launched 4 years ago and GH wasn't hot as it is nowadays, so it's not a surprise it isn't there. The idea of the ICG is that the work will entirely done (mostly) through GH so yes, we'll need the tool to help the creation. I'll add it to http://w3c.github.io/charter-html/html-plan.html#steps

**Comment by darobin** [comment]
On 04/06/2015 23:35 , Ade Bateman wrote:

> So the goal is not to have a new custom CONTRIBUTING.md for
> each repo.

We will definitely have a standard CONTRIBUTING.md across the board.

> Secondly, I want to have tooling that allows us to track what
> contributions have been made into CG repos. This means having an index
> of the repos that contain proposals for the CG.

That is certainly the plan; we need that if we want to track 
contributions anyway.

> My preference is that
> these are in one organization to make finding them easier rather than
> being scattered across random people's personal repos.

The problem with using an organisation is the overhead involved in 
managing access rights. We have to do this for the "w3c" organisation, 
it's not huge but it's not negligible. It is also a barrier to entry.

I think it's easier for people to use their own repos, we just need to 
make sure that we have the all. We need to have that information whether 
it's an organisation or personal so we can easily have an index page 
that lists all the repos. Likewise, we can automatically publish the 
specs somewhere centralised.

> Thirdly, I would like to be able to have tooling that understands the
> GitHub ID of CG participants. This way we can periodically crawl the
> contributions into CG repos and make sure that people have signed up to
> the CG.

That's planned, too. And we don't need to crawl, GitHub hooks can tell us!

## 

Robin Berjon - http://berjon.com/ - @robinberjon
