### ISSUE TITLE
cg-charter: clarify "repository" used for proposals

### ISSUE THREAD

**Issue by AFBarstow** [w3c/charter-html#28]
Re the version of the WPI-CG charter I am reading now (which I believe is (1)), the use of "repository" is a bit unclear:
1. "Each proposal will be discussed in its own GitHub repository."
2. "The group will conduct all of its technical work on its GitHub repository."

Is the expectation all CG proposals must be in the CG's repository? If so, it appears 1. above should be  changed to something like s/in its own/in the CG's/. 

(1) https://github.com/w3c/charter-html/blob/9e8d3180e6392ba87eb4838e76e545ec936ef64e/incubator-cg-charter.html

**Comment by plehegar** [comment]
The idea is to have a set of repository, one per proposal, thus the "own repo" wording, but I agree this needs clarification. How about:
"Each proposal will have a Github repository associated, and the proposals will be in their dedicated GitHub repositories".

**Comment by AFBarstow** [comment]
@plehegar so the expectation is the following?

[[
Each proposal will have its own repository within the CG's Github repository.
]]

**Comment by plehegar** [comment]
@AFBarstow yes
