### ISSUE TITLE
cg-charter: clarify non-use of the "contrib" list

### ISSUE THREAD

**Issue by AFBarstow** [w3c/charter-html#29]
Re the version of the WPI-CG charter I am reading now (which I believe is (1)), the section http://w3c.github.io/charter-html/incubator-cg-charter.html#process indicates _standard_ CG processes apply but it appears this CG will not use a "contrib" mail list for contributions. I don't view not using the contrib list as an issue per se but this deviation from standard _practice_ should be clearly documented. For example, adding something like the following sentence to this section:

[[
Note: this CG will not use a _contrib_ e-mail list for contributions since all contributions will be tracked via Github mechanisms (f.ex. pull requests).
]]

(1) https://github.com/w3c/charter-html/blob/9e8d3180e6392ba87eb4838e76e545ec936ef64e/incubator-cg-charter.html

**Comment by plehegar** [comment]
sounds good to me.

**Comment by marcoscaceres** [comment]
Agree. This seems good.
