### ISSUE TITLE
Test based standardization

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-html#3]
An alternate for make decisions about transitions from ICG to WG:

ideas move from the incubator after there exists a test plan and evidence that the exit criteria will be met.

**Comment by darobin** [comment]
I'm not sure that a test plan is good. How about the beginning of a test suite? (That has, by judgement call, to be better than a token effort.)

What would you consider evidence for the exit criteria? Expression of interest from two implementers?

**Comment by adrianba** [comment]
I don't think we necessarily need to be so prescriptive. There needs to be evidence that the proposal has a future. What that evidence is may vary for different cases.

**Comment by chaals** [comment]
In general we have a more test-based approach, waiting to accept changes into mainline specs until there is implementation. This isn't universal - we don't require it for the Shadow DOM and custom elements specs, for example.

We'll see which approach delivers better specs. I agree with @adrianba that we shouldn't try to be too prescriptive in the charter.
