### ISSUE TITLE
[charter] how are contributions made - text unclear

### ISSUE THREAD

**Issue by wayneca** [w3c/charter-html#33]
Proposed WebPlatform CG Charter says:

> Any suggestions, pull requests, issues, or comments made about a proposal fall under the CLA.
> Editors of feature proposals must ensure that no contributions are adopted from anyone 
> who is not a member of the community group.

This is vague.  Comments where?  Not a tweet.  It's also false.  The CLA says "intentionally submit for inclusion in the Specification, and which Contribution is actually included in the Specification" in the definition of Contribution.  So someone in an Issue saying a proposal should never be published as a CG Specification (CG Specifications are what the CLA actually applies to) is likely not intentionally submitting anything for inclusion in the Specification, even if they say something that would improve it.  Contributions are only things that do get included in the Spec.

I think that sentence should be replaced with something like:

[[
Contributions are made in GitHub Issues (including meeting minutes) or pull requests or commits, but always result in pull requests and commits in the GitHub repository that change the proposal.  Contributor's GitHub usernames must be listed in the comment in a GitHub pull request or commit.  The format to use should be a JSON object: 
{Contributors: "githubusername1","githubusername2"]}.
Committers of feature proposals must ensure that no contributions are adopted from anyone 
who is not a member of the Community Group.
]]

This also changes "Editors" to "Committers" in that last sentence.  The Editor could be the only Committer, but the proposal could also replace a dominant Editor with committers who have earned that status through their contributions, having a more distributed control than Editor owns it.

The whole thing about Contributing should move out of the Scope section and into the Contribution Mechanics section.  The last 2 sentences in the current Scope section have nothing at all to do with Scope.

**Comment by marcoscaceres** [comment]
```
to use should be a JSON object:
{Contributors: "githubusername1","githubusername2"]}.
Committers of feature proposals must ensure that no contributions are adopted from anyone
who is not a member of the Community Group.
```

The JSON above is not needed (and the JSON is also invalid;)). Contributions are attached to the commit via the email address of the contributor. A PR can contain multiple commits from multiple people, each of which is tracked to a particular person (including which commit changed what in a file - and is directly viewable with `git blame` - even across versions so you can see the full evolution of a document).

**Comment by marcoscaceres** [comment]
For example: 

![screenshot 2015-06-05 18 48 57](https://cloud.githubusercontent.com/assets/870154/8016604/923ef2d2-0bb3-11e5-8b0c-a51b1b09a7b6.png)

**Comment by darobin** [comment]
I don't think that tracking individual commits is the best approach. It may be that someone hashed out a working solution in an issues thread which you implemented in a PR. Under IPR rules, that person _is_ a contributor.

That's no reason to go embedding some JSON, though, that's far too error-prone. The rules should be:
- The originator of the PR is a contributor
- Whoever is listed with `+@username` on a line of its own is a contributor (in any comment, so long as the PR is open)
- Whoever is listed with `-@username` on a line of its own is removed from the contributors list (to fix errors).

That's easy to automate. The PR can be flagged as safe or not with that information alone.

**Comment by wayneca** [comment]
That would be good.  That should be in the required CONTRIBUTING.md file so its the same everywhere so it can be automated. To make sure people are aware they need to do it, the Charter probably should mention that all contributors must be listed in PR comments and that the format is in the CONTRIBUTING.md file.

**Comment by marcoscaceres** [comment]
@darobin, where is the CONTRIBUTING.md file housed? Let's just add: 

"In the case where contribution has ideas originating from more than the person that put together the PR, please include a code comment that lists the github username of the contributor(s). This should be in the format `+@username1 +@username2 +@username3 ...`".

**Comment by darobin** [comment]
@marcoscaceres The file is [over there](https://github.com/w3c/ash-nazg/blob/master/templates/CG-contributing.md) but the best part is that it _already_ does that.

**Comment by marcoscaceres** [comment]
Then, let me ask you this, Mr @darobin (if that is your real name) ... why, then, why?? why is it that this bug is still, you know, OPEN!

**Comment by darobin** [comment]
I would like to let @wcarr decide if his request has been properly addressed :)

**Comment by plehegar** [comment]
one reason is because I didn't go through the issues to properly close them...

**Comment by wayneca** [comment]
It needed to either be in the charter or else the charter needed to point to the contributing file and say that file is required in any GitHub repository.  There are also different versions of this.  The one Robin pointed to and one Wendy has been working on.  I like Wendy's better.

> If you are not the sole contributor to a contribution (pull request), please identify 
> all contributors in the commit message. In the commit, include on a new line,
> 
> Contributors: +@githubusername1, +@githubusername2, ...

People often don't read rules, but if they Wendy's version, it's clear what it means.  Having the word "Contributor" there makes it clearer.

**Comment by wayneca** [comment]
I agree, this one should be closed.
