### ISSUE TITLE
Timed media is not required to drive low level APIs

### ISSUE THREAD

**Issue by cwilso** [w3c/charter-html#37]
I believe it is pointless to separate out timed media APIs unless it is an absolute requirement that they describe the low level APIs - particularly audio and video i/o device access and streaming - necessary in the bedrock.  Without this being a core focus for the group, I think it should simply be part of the megagroup with everything else.

This is currently mentioned in the charter, but only as a "may produce".

**Comment by adrianba** [comment]
This is mostly because I didn't have the detail to propose it as will produce. If you have thoughts for how this should be structured based on your WebAudio experience I would happily make a pull request to add this in. Any other feedback on how to flesh out the detail would be wonderful.

**Comment by plehegar** [comment]
s/may/will/ and move into "Recommendation-Track Deliverables" from "Other Deliverables"
