### ISSUE TITLE
Name of "intent to standardize"

### ISSUE THREAD

**Issue by cwilso** [w3c/charter-html#4]
Reported by Adrian.  Name is a bit uncomfortable.

**Comment by plehegar** [comment]
The name may be misrepresented as "Look, this will get standardized because there is an intent", while an intent doesn't mean it will get supported.
proposed name is "Proposal for standardization"

**Comment by adrianba** [comment]
The template should be completed when the spec is ready to transition to a WG. One idea we had was "ready to review". During discussions, Ted suggested "Request to transition", which I think might work.

**Comment by plehegar** [comment]
Renamed to request to transition

**Comment by plehegar** [comment]
https://github.com/w3c/charter-html/commit/eab26362b659a37881f46884d4d8d1147f4a5cf2

**Comment by adrianba** [comment]
@rubys [points out](/w3c/charter-html/issues/21#issuecomment-104390405) in #21 that the similarity between [request to transition](http://w3c.github.io/charter-html/request-to-transition.html) and [transition request](http://www.w3.org/2005/08/01-transitions.html#reqs-satisfied) might be confusing.

**Comment by plehegar** [comment]
The CG charter talks about "migration to a W3C Working Group". How about "intent to migrate" then?

**Comment by darobin** [comment]
+1

**Comment by plehegar** [comment]
@marcoscaceres got an opinion on this one?

**Comment by LJWatson** [comment]
+1

**Comment by marcoscaceres** [comment]
Intent to migrate works for me.

**Comment by cwilso** [comment]
WFM.
