### ISSUE TITLE
New work should first be done in the Incubator CG before being added to WG deliverables

### ISSUE THREAD

**Issue by adrianba** [w3c/charter-html#42]
We should move to a model where the expectation is that WG track work has first been matured through the CG process. We should aspire to having many many ideas incubated and as a consequence some will naturally fall by the wayside. I would like this filtering to happen before adding something to the Recommendation track. We should refer people with new proposals to the ICG and adopt mature proposals once they have proven momentum.

**Comment by plehegar** [comment]
merged.

**Comment by dwsinger** [comment]
> On Jun 17, 2015, at 17:20 , Ade Bateman notifications@github.com wrote:
> 
> We should move to a model where the expectation is that WG track work has first been matured through the CG process.

I agree, but I think this should say “for example, through the CG process”.  I think we’re still willing to entertain well-formed proposals that come in via other routes (e.g. member submission) (and indeed, the incubator CG is not the only possible CG, just the easy/preferred/default).

> We should aspire to having many many ideas incubated and as a consequence some will naturally fall by the wayside. I would like this filtering to happen before adding something to the Recommendation track. We should refer people with new proposals to the ICG and adopt mature proposals once they have proven momentum.
> 
> —
> Reply to this email directly or view it on GitHub.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by adrianba** [comment]
>  I think we’re still willing to entertain well-formed proposals that come in via other routes

In my pull request I wrote, "or another similar incubation phase."
