### ISSUE TITLE
[webapps charter] proposed charter removes limits on scope/deliverables

### ISSUE THREAD

**Issue by wayneca** [w3c/charter-html#44]
Scope of Web Apps in Charter is anything needed in any app in a Browser and also anything needed on the server side.  So, it's anything an app of any sort could need to do.   That's what it said before, but that was limited by a set of deliverables that could not be expanded without rechartering.

I think what happened was language that made the deliverables seem unlimited was left in: "The working group will deliver at least the following:", but the text that limited that later in the current charter was removed.

In the old Charter, the reason it was "at least" was it was allowed to transfer specs from the HTML WG."the WebApps WG may opt to take on a limited number of specifications which were initially part of the HTML5 specification that have been split off"

It was expressly not allowed to add any other specifications without rechartering: "Other specification proposals may be identified by new submissions from Members, or by market research. These deliverables will require rechartering the Working Group."

That sentence should be added back at the end of the list of spec deliverables.  Otherwise, this group has unlimited scope and all participating organizations have to license all essential patent claims in all specs, whatever they are, unless they specifically detect and exclude patent claims (which is too burdensome to be practical as a way to allow adding arbitrary specs).

"at least" should also be removed from: " "The working group will deliver at least the following:""  That meant specs could be added from the HTML WG, which would no longer apply when it is merged into this WG.

**Comment by adrianba** [comment]
I proposed a similar change yesterday in #43. I've updated the pull request to also remove the "at least" phrasing.

**Comment by plehegar** [comment]
merged.

**Comment by wayneca** [comment]
this was fixed, so should be closed
