### ISSUE TITLE
Timed Media WG and maintenance of HTMLMediaElement interface

### ISSUE THREAD

**Issue by tidoust** [w3c/charter-html#46]
It is my understanding that the Timed Media WG will continue the work done by the HTML Media Task Force and as such maintain the HTMLMediaElement and related interfaces (e.g. MediaController) in HTML5.

If so, the current draft charter is not explicit about that and rather seems to suggest that the (new) WebApps WG would handle that part as part of evolutions made to HTML5.

I suggest to clarify who will do what in that regard. Something like the following at the end of the "Deliverables" section perhaps?

"In addition, the Timed Media Working Group will maintain errata and new editions, as necessary, of media-related portions of HTML 5.0 for publication by the Web Applications Working Group."

...with a similar but reversed note in the WebApps draft charter next to "HTML 5.0" in the Specification maintenance list: "HTML 5.0 (the Timed Text Working Group will maintain media-related interfaces).

Also, shouldn't the WebApps draft charter have the Timed Text WG in its list of liaisons?

**Comment by adrianba** [comment]
I was thinking about something similar. We should be explicit in the Timed Media WG that future maintenance of the HTML5 media elements is a deliverable of the WG. Pull request #47 has my proposal for updating the Timed Media WG charter.

**Comment by plehegar** [comment]
The charter makes it explicit in the maintenance section. In addition, it also explicitly out of scope for the Web Platform WG.
