### ISSUE TITLE
[charters] text to make it easier to recharter to add deliverables

### ISSUE THREAD

**Issue by wayneca** [w3c/charter-html#57]
Rechartering to add deliverables is often considered too long and difficult.  A concern is that old issues, unrelated to the added deliverable can be rehashed when the charter is rechartered to make a simple deliverable addition.  When the Charter has not expired and the change is just to the deliverables list, rechartering could be just: edit the deliverables list, 4 week Advisory Committee Review of just the change, Director's assessment of consensus after the AC Review.

The DAP Charter being developed includes text asking that Review for rechartering to add deliverables  without changing duration consider just the change.  If WGs adopt this text in Charters it could help set a precedent for agile Charter updates for adding deliverables.  I suggest we add the text DAP is considering to the Timed Media and Web Platform Charters.

https://github.com/w3c/dap-charter/pull/14/files 

<h3>Adding new Recommendation-track deliverables</h3>

<p>If additional deliverables need to be added to the Charter before the Charter expires, the Working Group will prepare an updated Charter that differs only in deliverables. In the interest of agile spec development, the group requests that the Advisory Committee and Director restrict approval reviews for those Charter deliverables adjustments to just the changes in the Charter, rather than considering the entire Charter again for review.</p>

**Comment by dwsinger** [comment]
I agree, but rather than replicating this in every charter, wouldn’t it be better said once, applicable to everyone, in a central place?

(I know, you’re going to ask “like where?", and while in general I don’t like mixing rules and best practice, perhaps this belongs in the process?)

> On Jul 8, 2015, at 18:57 , Wayne Carr notifications@github.com wrote:
> 
> Rechartering to add deliverables is often considered too long and difficult. A concern is that old issues, unrelated to the added deliverable can be rehashed when the charter is rechartered to make a simple deliverable addition. When the Charter has not expired and the change is just to the deliverables list, rechartering could be just: edit the deliverables list, 4 week Advisory Committee Review of just the change, Director's assessment of consensus after the AC Review.
> 
> The DAP Charter being developed includes text asking that Review for rechartering to add deliverables without changing duration consider just the change. If WGs adopt this text in Charters it could help set a precedent for agile Charter updates for adding deliverables. I suggest we add the text DAP is considering to the Timed Media and Web Platform Charters.
> 
> https://github.com/w3c/dap-charter/pull/14/files
> 
> Adding new Recommendation-track deliverables
> 
> If additional deliverables need to be added to the Charter before the Charter expires, the Working Group will prepare an updated Charter that differs only in deliverables. In the interest of agile spec development, the group requests that the Advisory Committee and Director restrict approval reviews for those Charter deliverables adjustments to just the changes in the Charter, rather than considering the entire Charter again for review.
> 
> —
> Reply to this email directly or view it on GitHub.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by wayneca** [comment]
> I agree, but rather than replicating this in every charter, wouldn’t it be better said once, 
> applicable to everyone, in a central place?
> 
> (I know, you’re going to ask “like where?", and while in general I don’t like mixing rules 
> and best practice, perhaps this belongs in the process?)

Yes, absolutely it belongs in the W3C Process.  But, we shouldn't wait the year+ for that to happen.  For right now, I think it should be in WG Charters.  Experience with it would help convince any doubters (if there are any) that it works.  It would be helpful to put it in the Charter template marked with some note about deciding if they want it, so people know to at least consider it, and for W3C staff to tell people about if it isn't in proposed charters..

It's the same thing for the asynchonous decision making paragraph in Charters that ensures people worldwide can participate in decisions. That says that people have some number of days (7 or 10 in various Charters) to object to a decision made at a meeting (like a telephone call that is in the middle of the night for them), and then it is decided asynchronously - email, a poll, etc..  That should be in the W3C Process, but for now it's someone objecting to Charters that don't have it and getting it in every Charter. 

For either of those, W3C staff could form a staff policy, that they suggest it to whoever is requesting a Charter.  And eventually, we could get both in the Process.

**Comment by plehegar** [comment]
I made a pull request for this one but I do not believe that we can restrict that the Director or AC right to question the entire charter before sending to the AC or during a review at the moment. So, imho, adding the text would be in conflict with the Process, and the Process always wins. At the moment, I'm inclined not to merge the #68 

Note that we did partial review in the past, such as:
https://lists.w3.org/Archives/Member/w3c-ac-members/2011JanMar/0051.html
