### ISSUE TITLE
[TimedMedia Charter] Other Deliverables - need links and clarification

### ISSUE THREAD

**Issue by wayneca** [w3c/charter-html#58]
Section 3.3 Other Deliverables refers to other CGs and Specs that could be moved to the Time Media WG.  It isn't always clear if those are particular specs or where they are .  There should be links to any CGs or particular specs mentioned. e.g. is " the current Transcript proposal" http://w3c.github.io/html-transcript/html-transcript-src.html ?

> .Low Level Audio and Video support
> The Timed Media Working Group may work on low-level media APIs to support
> the work of the Audio and Web Real-Time Communications Working Groups

An example may be good to know what that meant, since it's presumably lower level than what those WGs work on now.

Some groups, specs mentioned.

Timed Text WG   http://www.w3.org/AudioVideo/TT/   

WebVTT specification -   http://www.w3.org/TR/2015/WD-ttml2-20150212/ 

Media Resource In-band Tracks Community Group  https://www.w3.org/community/inbandtracks/  No Chair, no Charter, no CG publications - makes it hard to evaluate what this means for licensing obligations in the Timed Media WG. It's basically whatever that group publishes can be put in the Timed Media WG without rechartering.

Audio WG -  http://www.w3.org/2011/audio/

WebRTC WG -  http://www.w3.org/2011/04/webrtc/ 

Second Screen Presentation Working Group - http://www.w3.org/2014/secondscreen/ 
what does "coordinate" mean in "The Timed Media Working Group may coordinate work on secondary screen playback with the Second Screen Presentation Working Group."  Does this mean that Second Screen is also in scope of this WG?  or does it mean not producing a spec but playing some coordination role?  If it means that this proposed group could adopt the specs from second screen if that group wanted to give them up, it should say that.  As it is, it isn't clear if this means it could produce a competing spec.

**Comment by silviapfeiffer** [comment]
Might also be interesting to note that the texttracks CG has produced a conversion spec at https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/608toVTT.html and not just the WebVTT spec.

**Comment by plehegar** [comment]
@silviapfeiffer yes but, unless I'm mistaken, I don't think we'd want to put that note on the REC track. correct?

**Comment by plehegar** [comment]
Doesn't solve the second screen question yet.

**Comment by plehegar** [comment]
Should be all set now

**Comment by silviapfeiffer** [comment]
Yes, fair enough.
