### ISSUE TITLE
Wider scope for the Working Group

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-html#6]
Should we have a wider scope for the Working Group itself?
The idea of merging HTML and Web Apps has been discussed by some for a while and has a lot of pros and cons. The main reason not to do it is to avoid messing up with the WebApps group itself.

**Comment by plehegar** [comment]
See also http://github.adrianba.net/webstandards/HTML-innovation-vs-maintenance.html

**Comment by LJWatson** [comment]
The HTML plan is simple, and logistically that's a good starting point. If we put the plan into action as it stands we'll be able to iron out any initial wrinkles, make adjustments, and learn from the experience.

We'd then be in a better position to look at whether expanding the WG makes sense (either for HTML or WebApps).

**Comment by rubys** [comment]
https://github.com/adrianba/webstandards/issues/2

**Comment by plehegar** [comment]
https://github.com/w3c/charter-html/issues/14

**Comment by plehegar** [comment]
See https://github.com/w3c/charter-html/issues/14#issuecomment-111583763
