### ISSUE TITLE
Embrace modern spec dev practices

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/charter-html#7]
I have a concern about this: 

> "Each document worked in the Working Group should have two branches: a development one and a stable one. Daily work is expected to happen on the dev branch, including bug fixing. When applicable, changes must be backported to the stable branch. It is encouraged to have different individuals between the dev and the stable branches. The goal of the development branch is to encourage convergence of the implementations towards interoperability as well as introduce new function. The goal of the stable branch is to document expected interoperability."

That doesn't match how we do development on GH. It would be better to have 1 branch, which get pushed to TR and new features are submitted through PR and get peer-reviewed before landing in the spec. That way, anyone interested can review a PR before it lands ... and it could be a rule that you can't land anything without at least 1 review (preferably maybe with two ":+1:").

**Comment by plehegar** [comment]
First, by branches, I didn't necessarily mean "github branches". How to solve the dev vs stable branch handling is up for the Group to figure out.
Second, without a stable branch, you could get stuck in the living/editor's draft world, ie you never get to Recommendation status. So, I have no problem with a peer review system for developing the specs as you suggest. The text was meant to address how to get to Rec while dealing with continuous flow of new features.

**Comment by plehegar** [comment]
Or maybe you mean to suggest that, in addition to the stable and dev branches, we should adopt a peer review? I'd be fine with that.

**Comment by marcoscaceres** [comment]
> First, by branches, I didn't necessarily mean "github branches". How to solve the dev vs stable branch handling is up for the Group to figure out.

To be clear, would it be ok to say that feature branches serve as "editor drafts"? It would be very messy to have a "ed" branch with random proposals (irrespective of git being used or not). 

> Second, without a stable branch, you could get stuck in the living/editor's draft world, ie you never get to Recommendation status. 

This is a risk, yes: but it's primarily caused by the process, not because of the branching model. For instance, it's extremely risky to move to CR because the Editors are blocked from fixing typos and small bugs during this phase (in a way that will end up on TR). Hence, I would imagine Editors would be reluctant to enter this phase until the specs have been long implemented and proved interoperable (or might not bother at all, because "the work is done and now it's just boring process"). 

> So, I have no problem with a peer review system for developing the specs as you suggest. The text was meant to address how to get to Rec while dealing with continuous flow of new features.

Ok, then I'm still worried that the text is overly prescriptive here. Can I recommend something like the following: 

"""
Technology being worked on in a Working Group will generally have stable and unstable features. An unstable feature is a proposal (e.g., spec text, IDL, example code, etc.) that doesn't yet have consensus from the group to be included into a specification. This can be because the feature has not received review from members of the Working Group, or because it merely serves as a straw-person proposal. Generally, unstable features should not appear in a specification. However, the Working Group may choose to include features into a specification that are not fully formed, but have consensus, to encourage and facilitate wide-review from the web community. 

Anyone is free to propose an unstable feature (e.g., as a pull request on GitHub, or as an email, etc.) and then work actively to getting consensus from the Group to move the feature into a specification as a stable feature. Thus, a stable feature is one that has been reviewed by members of the group and represents the consensus of members of the group (particularly with respect to implementability of a feature). Stable features introduce new functionality and encourage convergence of the implementations towards interoperability. This is not to say that stable features are free of bugs or are fully formed, just that they represent a shared understanding and consensus of the behavior or shape of a feature. Stable features can be refined over time, eventually reaching stability through proven interoperability and as reflected by the status of the document along the W3C's recommendation track (e.g, by entering the Candidate Recommendation phase).
"""

**Comment by marcoscaceres** [comment]
To be clear, the point is to avoid a "srcset" - where it was added to the spec by the Editor despite not having consensus in it's initial form. This caused _a lot_ of frustration from implementers and developers.

**Comment by darobin** [comment]
Two small notes:
- Concerning branch naming, we should say that any branch that isn't `master` should be considered a proposal of some sort.
- Concerning CR editors should have liberty to make editorial fixes, there is nothing that should prevent them there (process certainly doesn't). Ideally, we should avoid going to CR without having a lot of visibility over what is actually being implemented. In other words, I would recommend already having a test suite and a lot of passes, only using CR to tie up loose ends.

**Comment by adrianba** [comment]
I agree with @marcoscaceres that the main goal here is to avoid mixing unstable features with no consensus (that an editor just dreamed up) with agreed upon spec text. Early in the development of a spec (most likely in the incubator CG where there is less process) documents will have a lot more freedom. As we transition to the standards track, we want to be working on stabilising towards something shippable that web developers can begin to depend on. This means driving out the unstable proposals, just like we drive out the unstable code in order to ship. Sometimes there may be consensus to introduce and experimental feature that isn't yet stable and that should be okay.

In CR, I think editors should be free to add any non-normative changes. This might be editorial fixes or adding more code examples or clarifying language based on feedback from implementers. Basically anything that doesn't invalidate a technical review of the document.

An interesting case to consider where branching might be helpful is after publishing a v1 spec. We then begin work on v2 and because we're early in the process we introduce a bunch of unstable new features. Then we find an interop bug because the v1 spec was vague and shipping browsers need a clarification. Ideally we'd be able to update v1 with the fix while we work on v2 just like we do in software.

I think the vast majority of the times where we have had problems with v1 and v2 competing has been when it took too long to stabilise v1. With new features in v2 that becomes too attractive, especially when implementation happens, and then the value of v1 lapses. As long as we get v1 landed pretty quickly we can postpone most v2 work until we're ready and reduce problems here.

**Comment by marcoscaceres** [comment]
Agree with the versioning problem. I think it's a matter of scope or accepting that is something we need to proactively deal with (e.g., with WebIDL, which must constantly be updated to expose underlying ES functionality that is being developed on a different time frame, by a different consortium - while v1 of WebIDL kinda rots on TR). Small feature specs may stabilize faster, but new features may be added as developers find limitations with the design (e.g., wake lock API comes as an example, where "system" locks are now being requested in addition to "screen" locks). 

For problematic specs that are both stable and evolving, it might be worth while to seek IPR commitments on yearly snapshots once there is "good enough" evidence of interoperability (again, WebIDL is the perfect example here). Interop might not be perfect, but it might be "good enough" to RECOMMEND, with the proviso that the spec continues to evolve.

**Comment by darobin** [comment]
I completely agree.

In fact, I've been wondering if we couldn't move to having an "Interoperability" section in every Rec. Its goal would be to report on the state of interoperability at the time of shipping. It could go so far as to say things like "Feature foo in section 17 has no demonstrated interoperability whatsoever; for the time being it should therefore be considered informative."

This would require updates to Recs until such a time as interop is deemed sufficient. That's not necessarily a bad thing.

**Comment by adrianba** [comment]
I think it is most important that we create Recommendations with "good enough" evidence of interoperability and hopefully use failing tests as warnings to web developers rather than blockers to progress. Perhaps Recommendations can reference an implementation report that could publish subsequent versions without having to update the Rec. We should update the Rec when bugs are found that need to be fixed to record interop decisions where we don't want to wait for v.next.

**Comment by plehegar** [comment]
Current W3C implementation reports are harmful imho. It's a snapshot of implementations at a fixed point and they never get updated. They are only useful for the Director to make a decision on a given day. If we're going to reference them from W3C Recommendations, we'll need to have a way to generate them automatically imho.

Ideally, I'd like browser vendors to report their own test results, at their own pace. And the implementation report would be a view of those test results.

**Comment by marcoscaceres** [comment]
I agree with @plehegar. We might need much better tooling here (or we might need to just rely on crowd-sourced efforts like caniuse.com). In Mozilla's DOM team, we don't prioritize migrating our internal tests (e.g., Mochitests) to Web Platform tests. This makes it hard to contribute back to an implementation report because having web platform tests is not critical for us to ship features (hence we don't prioritize contributing back to an implementation report or the w3c - even if we want to, just no time or QA resources from my experience ).

//cc @jgraham - who might have some ideas about improving this situation a bit.

**Comment by adrianba** [comment]
> Current W3C implementation reports are harmful imho. It's a snapshot of implementations at a fixed point and they never get updated. They are only useful for the Director to make a decision on a given day. If we're going to reference them from W3C Recommendations, we'll need to have a way to generate them automatically imho.

If we can't get implementation reports updated then we shouldn't kid ourselves that putting this status information in the actual Recommendation document will somehow convince us to keep it up to date.

We need to encourage the culture change around how we get to Recommendation and what we do after that to keep things up to date.

**Comment by marcoscaceres** [comment]
I can't agree more. I've proposed relying on what developers already provide. What are some other options here?

**Comment by chaals** [comment]
Not sure there is a concrete action here, so closing the issue.
