### ISSUE TITLE
[group-charter] Provide context for "High level User Events"

### ISSUE THREAD

**Issue by AFBarstow** [w3c/charter-html#88]
The draft charter includes a "High level User Events" deliverable that lacks sufficient context to determine if its inclusion would be problematic or not (f.ex. for potential patent concerns). 

Is this a placeholder for IndieUI work/specs?

Is this about creating some type of "gestures" spec?

**Comment by plehegar** [comment]
This is a placeholder for IndieUI work. Now it may well be that the direction is going to be WAPA (Web Accessibility Platform API), thus not picking a winner in the charter.

**Comment by AFBarstow** [comment]
As written, I would expect the text to be insufficient for an IP analysis. As such, either remove that deliverable or strengthen it with more context and/or the clarification provided above. 

Every deliverable in this charter should have at least an Editor's Draft available; otherwise that work item should be deferred to some CG until the details are fleshed-out to the point an IP analysis can be done.

**Comment by plehegar** [comment]
The deliverable cannot be dropped. It's part of a long discussion that happened within the scope of the WAI rechartering. The AC is actually requesting for that deliverable to be there. I also don't see how to strengthen the wording: this is about enabling the use to interact with the app from a high level perspective (such as zooming).
