### ISSUE TITLE
[group-charter] Location of WG's home page

### ISSUE THREAD

**Issue by AFBarstow** [w3c/charter-html#99]
The draft charter uses the consortium's "date space" for the group's home page (http://www.w3.org/2015/@@@@/). Please use GH or w3.org/wiki/...  to facilitate broad collaboration in keeping that information current.

**Comment by plehegar** [comment]
I'd rather leave this up in the air at the moment. There is a dashboard project on the way within Modern Tooling, so let's see what they come up with.

**Comment by AFBarstow** [comment]
You've convinced me GH should be used ;-). Rather than split the group's admin resources among different services/URLs, let's drink all the kool-aid and use Github for the group's Home Page too. (Afterall, the draft charter already has related placeholders like https://w3c.github.com/webplatform-wg/PubStatus.md)

**Comment by plehegar** [comment]
Eh, you should go easy on that kool-aid. :)
Note that using http://www.w3.org/2015/@@@@ doesn't mean that we can't use github.
See for an example:
 http://www.w3.org/2010/webperf/board/
